// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIqYWh5xGhLS_ztsOperBSZq-hx63YW40',
    appId: '1:934131018769:web:ec9350604f656e41c715b0',
    messagingSenderId: '934131018769',
    projectId: 'gymapp-56f44',
    authDomain: 'gymapp-56f44.firebaseapp.com',
    storageBucket: 'gymapp-56f44.appspot.com',
    measurementId: 'G-3W52N522YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo3BNqcB9PiWTOmV5JWIymn2Mr7arckIQ',
    appId: '1:934131018769:android:48635ef085e7668fc715b0',
    messagingSenderId: '934131018769',
    projectId: 'gymapp-56f44',
    storageBucket: 'gymapp-56f44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcc_d_82Qc7rp_JOhzhCkUoQcGWjlNeIM',
    appId: '1:934131018769:ios:8d2eaa9560dd8f7dc715b0',
    messagingSenderId: '934131018769',
    projectId: 'gymapp-56f44',
    storageBucket: 'gymapp-56f44.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );
}
